### ISSUE TITLE
W3 - Review Ticket - Jonathan Lin

### ISSUE THREAD

**Issue by armarmgc** [armarmgc/group-m#10]
# Score: 5/5, Grader: Prisha Maiti
Team score: 3/3
Individual score: 2/2
[Team repo](https://github.com/armarmgc/group-m)
[Team plan](https://armarmgc.github.io/group-m)
[Github pages link](https://armarmgc.github.io/datastruct-proj/)

**Comment by PrishaMaiti** [comment]
Score: 2/2
GitHub review pages that document key learnings using code snippets
Calculator page that shows highlights of work: Page shows code snippets of both Design and Learnings as well as a few sentences to explain the code. Page looks really organized. (+.5)
Calculator Code with optional extra credit functions, Replit Runtime, with runnable (no input) Test Data, and input option: Calculator code is present and user input returns correct results. Test cases above user input are also mathematically correct, which shows that the code is doing its job. Extra credit functions were not there. (+1.5)
