### ISSUE TITLE
W4 - Sorts and Analysis - Jonathan Lin

### ISSUE THREAD

**Issue by armarmgc** [armarmgc/group-m#11]
# Score: 5/5, Grader: Chenxin Ni

Individual score: 5/5

[Github pages](https://armarmgc.github.io/datastruct-proj)

**Comment by chenxin-chex** [comment]
Objective 2 scoring: **5/5**

 - [25/25%] Github pages have analysis of sort 
![image](https://user-images.githubusercontent.com/55467785/161594355-a748066a-1b13-440b-94dd-a1f1c8f6fb24.png)

 - [25/25%] Github page have big o notation and final judgement
![image](https://user-images.githubusercontent.com/55467785/161594385-73a1038c-fb60-486b-af1d-16c685eb9689.png)


 - [25/25%] Replit shows 4 different sorts (bubble, insert, merge, select)
![image](https://user-images.githubusercontent.com/55467785/161593826-bf21414e-69ee-4838-a869-6542edaa090f.png)

 - Created and sorted own data structure (list)
 - [25/25%] Replit is organized into folders and Github pages have weeks
