### ISSUE TITLE
Initial Login System

### ISSUE THREAD

**Issue by iskapoor** [armarmgc/group-m#19]
- [x] Add login authentication
- [x] Add register for user creation

**Comment by algolg** [comment]
https://github.com/armarmgc/group-m/commit/4c7e23148b00f1a8cd89456447cc3f14564535d3

**Comment by armarmgc** [comment]
Trying to implement a new user storage process by storing email, username, and password hash in the `data/auth` file.

Sample file:
```

user1@email.com
user1
$2a$10$Qe1mFMXl4bn39OrtuY4o9uxbk.CASkdcy/f1AkYlhkxjM3kDBmkAO

user2@email.com
user2
$2a$10$gYNWfYFXXHaM9bF.LzW03uoIsRhgQdcVBxoQNBnP18ImyvNIYjT9O

user3@email.com
user3
$2a$10$4ricp.nooWDbwCkdWYuuoeQY6emYt2pPMSJSp5b0uP68j6VqDXiqq
```

Since this is a very big change that is still in progress, created the `register` branch for this.

Progress:
4b4e7f07283cdcb98e64b5e28b665a2d787eed83
