### ISSUE TITLE
Login UI

### ISSUE THREAD

**Issue by iskapoor** [armarmgc/group-m#20]

**Comment by armarmgc** [comment]
Created design for login page
12c24d2f596d8292211dcff81387aafab2e86bd1

<img width="505" alt="login_design" src="https://user-images.githubusercontent.com/57158423/168329077-6758cc10-5c19-4beb-863f-eb804be3fd2b.png">

**Comment by armarmgc** [comment]
Create designed error message
930cb59a2bc0f5b5ca7b807377a310c86aa102b9

<img width="512" alt="design_error_msg" src="https://user-images.githubusercontent.com/57158423/168333883-3b2555d1-ecfd-4e54-ae3f-c3afb7a2d2df.png">
