### ISSUE TITLE
Crossover Review Ticket

### ISSUE THREAD

**Issue by iskapoor** [armarmgc/group-m#7]
Requirement 1: 
![image](https://user-images.githubusercontent.com/86839713/158861278-175d1fc1-b1fa-48a4-af4b-5cb6fabe7ed1.png)
[on the wiki](https://github.com/armarmgc/group-m/wiki)

Requirement 2: 
[scrum board](https://github.com/armarmgc/group-m/projects/1)

**Comment by jm1021** [comment]
Fish site.  Good idea from 1st week.  No Akhil for progress.  

.8/1
