### ISSUE TITLE
W2 - Group Review

### ISSUE THREAD

**Issue by algolg** [armarmgc/group-m#9]
https://armarmgc.github.io/group-m/

**Comment by jm1021** [comment]
Breed and buy fish website.  Business side to those who buy and shell fish.  Forum on site that source from other Forums.  

Basic idea is Fish, Tanks, Decor, Chemicals.    Plus, Forum Tab.

Has trail of communication for requirements.  Roles have been identified. Thinking about money and shipping.

Database, Hosting, and Licensing discussed.
